(()=>{'use strict';
const KEY='lvpt-proof-studio-v2', S={proofs:[],id:null,t:null};
const $=id=>document.getElementById(id);
const E={list:$('list'),search:$('search'),empty:$('empty'),editor:$('editor'),title:$('title'),saved:$('saved'),client:$('client'),contact:$('contact'),email:$('email'),phone:$('phone'),event:$('event'),date:$('date'),location:$('location'),label:$('label'),note:$('note'),notify:$('notify'),cc:$('cc'),dc:$('dc'),fc:$('fc'),ready:$('ready'),chips:$('chips'),cards:$('cards'),foods:$('foods'),drinks:$('drinks'),chipEmpty:$('chipEmpty'),cardEmpty:$('cardEmpty'),foodEmpty:$('foodEmpty'),drinkEmpty:$('drinkEmpty'),toast:$('toast'),modal:$('modal'),frame:$('frame')};
const uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8), now=()=>new Date().toISOString();
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{if(!d)return'';let a=d.split('-').map(Number);return a.length===3?new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(new Date(a[0],a[1]-1,a[2])):d};
const safe=(s,f='portal')=>(s||f).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||f;
function blank(){return{id:uid('proof'),client:'',contact:'',email:'',phone:'',event:'',date:'',location:'',label:'Round 1',note:'Please review the event options below and make your selections.',notificationEmail:'book@pokertraininglasvegas.com',chips:[],cards:[],foods:[],drinks:[],created:now(),updated:now()}}
function migrate(p){p.chips=Array.isArray(p.chips)?p.chips:[];p.cards=Array.isArray(p.cards)?p.cards:[];p.foods=Array.isArray(p.foods)?p.foods:[];p.drinks=Array.isArray(p.drinks)?p.drinks:[];p.notificationEmail=p.notificationEmail||'book@pokertraininglasvegas.com';p.note=p.note||'Please review the event options below and make your selections.';return p}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'[]');S.proofs=Array.isArray(x)?x.map(migrate):[]}catch{S.proofs=[]}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S.proofs));E.saved.textContent='Saved locally'}catch{E.saved.textContent='Working in memory'}}
function toast(m){E.toast.textContent=m;E.toast.classList.add('show');clearTimeout(S.t);S.t=setTimeout(()=>E.toast.classList.remove('show'),2200)}
function cur(){return S.proofs.find(p=>p.id===S.id)||null}
function touch(){let p=cur();if(!p)return;p.updated=now();E.saved.textContent='Saving…';clearTimeout(touch.t);touch.t=setTimeout(()=>{save();renderList()},180)}
function create(){let p=blank();S.proofs.unshift(p);S.id=p.id;save();render();setTimeout(()=>E.client.focus(),30)}
function renderList(){let q=E.search.value.trim().toLowerCase(),arr=[...S.proofs].sort((a,b)=>new Date(b.updated)-new Date(a.updated)).filter(p=>!q||`${p.client} ${p.contact||''} ${p.email||''} ${p.event} ${p.location||''}`.toLowerCase().includes(q));E.list.innerHTML=arr.length?arr.map(p=>`<button class="proofBtn ${p.id===S.id?'active':''}" data-id="${p.id}"><strong>${esc(p.client||p.event||'Untitled Portal')}</strong><span>${esc([p.event,p.date?fmt(p.date):'',p.label].filter(Boolean).join(' · ')||'Saved locally')}</span></button>`).join(''):'<div class="assetEmpty">No client portals yet</div>';E.list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{S.id=b.dataset.id;render();scrollTo({top:0,behavior:'smooth'})})}
function render(){renderList();let p=cur();if(!p){E.empty.classList.remove('hidden');E.editor.classList.add('hidden');return}E.empty.classList.add('hidden');E.editor.classList.remove('hidden');['client','contact','email','phone','event','date','location','label','note'].forEach(k=>E[k].value=p[k]||'');E.notify.value=p.notificationEmail||'book@pokertraininglasvegas.com';E.title.textContent=p.client||p.event||'Untitled Portal';E.saved.textContent='Saved locally';renderOpts();status()}
function status(){let p=cur();if(!p)return;E.cc.textContent=p.chips.length+' / 10';E.dc.textContent=p.cards.length+' / 10';E.fc.textContent=(p.foods.length+p.drinks.length)+' total';let count=p.chips.length+p.cards.length+p.foods.length+p.drinks.length;E.ready.textContent=!count?'Add options to begin':!(p.client||p.event)?'Add client or event name':'Ready to preview & export'}
function up(kind,id,field,img,label){return`<label class="upload ${kind} ${img?'has':''}">${img?`<img src="${img}" alt="${esc(label)}">`:''}<input type="file" accept="image/png,image/jpeg,image/webp" data-img="${kind}:${id}:${field}"><span class="upTxt"><b>Upload artwork</b>PNG, JPG or WEBP</span></label>`}
function tools(kind,x,i,arr){return`<div class="tools"><button class="tiny" data-act="up" ${i===0?'disabled':''}>↑</button><button class="tiny" data-act="down" ${i===arr.length-1?'disabled':''}>↓</button><button class="tiny red" data-act="remove">Remove</button></div>`}
function chipHTML(x,i){let p=cur();return`<article class="opt" data-kind="chip" data-id="${x.id}"><div class="optHead"><strong><span class="num">${String(i+1).padStart(2,'0')}</span>Chip Option ${i+1}</strong>${tools('chip',x,i,p.chips)}</div><div class="optBody"><div>${up('chip',x.id,'image',x.image,x.title)}</div><div class="fields"><div class="row2"><label><span class="lab">Option Name</span><input class="mini" data-f="title" value="${esc(x.title)}" placeholder="Black + Gold Circuit"></label><label><span class="lab">Denomination / Identifier</span><input class="mini" data-f="denom" value="${esc(x.denom)}" placeholder="$100 or Event Chip"></label></div><label><span class="lab">Client-Facing Notes</span><textarea class="mini ta" data-f="desc" placeholder="Matte black base, gold accents…">${esc(x.desc)}</textarea></label><div class="row2"><label><span class="lab">Color / Finish <em>optional</em></span><input class="mini" data-f="finish" value="${esc(x.finish)}" placeholder="Matte black / metallic gold"></label><label><span class="lab">Internal Reference <em>hidden</em></span><input class="mini" data-f="ref" value="${esc(x.ref)}" placeholder="CH-01"></label></div></div></div></article>`}
function cardHTML(x,i){let p=cur();return`<article class="opt" data-kind="card" data-id="${x.id}"><div class="optHead"><strong><span class="num">${String(i+1).padStart(2,'0')}</span>Card Option ${i+1}</strong>${tools('card',x,i,p.cards)}</div><div class="optBody cards"><div class="pair"><div>${up('card',x.id,'front',x.front,x.title+' front')}<div class="cap">FRONT</div></div><div>${up('card',x.id,'back',x.back,x.title+' back')}<div class="cap">BACK</div></div></div><div class="fields"><div class="row2"><label><span class="lab">Option Name</span><input class="mini" data-f="title" value="${esc(x.title)}" placeholder="White Tech Grid"></label><label><span class="lab">Card Type / Stock</span><input class="mini" data-f="stock" value="${esc(x.stock)}" placeholder="PVC / casino grade"></label></div><label><span class="lab">Client-Facing Notes</span><textarea class="mini ta" data-f="desc">${esc(x.desc)}</textarea></label><div class="row2"><label><span class="lab">Finish / Treatment</span><input class="mini" data-f="finish" value="${esc(x.finish)}" placeholder="Black core / smooth finish"></label><label><span class="lab">Internal Reference <em>hidden</em></span><input class="mini" data-f="ref" value="${esc(x.ref)}" placeholder="CD-01"></label></div></div></div></article>`}
function fbHTML(x,i,kind){let p=cur(),arr=kind==='food'?p.foods:p.drinks,label=kind==='food'?'Food':'Beverage';return`<article class="opt" data-kind="${kind}" data-id="${x.id}"><div class="optHead"><strong><span class="num">${String(i+1).padStart(2,'0')}</span>${label} Option ${i+1}</strong>${tools(kind,x,i,arr)}</div><div class="optBody fb"><div>${up(kind,x.id,'image',x.image,x.title)}</div><div class="fields"><div class="row2"><label><span class="lab">Option Name</span><input class="mini" data-f="title" value="${esc(x.title)}" placeholder="${kind==='food'?'Modern Tuna Nigiri':'Premium Open Bar'}"></label><label><span class="lab">Category</span><input class="mini" data-f="category" value="${esc(x.category)}" placeholder="${kind==='food'?'Premium Bites':'Bar Package'}"></label></div><label><span class="lab">Client-Facing Description</span><textarea class="mini ta" data-f="desc">${esc(x.desc)}</textarea></label><div class="row3"><label><span class="lab">Dietary / Detail <em>optional</em></span><input class="mini" data-f="detail" value="${esc(x.detail)}" placeholder="Vegan / GF / Premium"></label><label><span class="lab">Client Display Price <em>optional</em></span><input class="mini" data-f="price" value="${esc(x.price)}" placeholder="$18 pp / Included"></label><label><span class="lab">Internal Cost <em>hidden</em></span><input class="mini" data-f="cost" value="${esc(x.cost)}" placeholder="$135 tray"></label></div><div class="row2"><label><span class="lab">Internal Reference <em>hidden</em></span><input class="mini" data-f="ref" value="${esc(x.ref)}" placeholder="FB-01"></label><div class="checkrow"><label class="check"><input type="checkbox" data-check="featured" ${x.featured?'checked':''}> Feature / WOW item</label><label class="check"><input type="checkbox" data-check="priceVisible" ${x.priceVisible?'checked':''}> Show price</label></div></div></div></div></article>`}
function renderOpts(){let p=cur();E.chips.innerHTML=p.chips.map(chipHTML).join('');E.cards.innerHTML=p.cards.map(cardHTML).join('');E.foods.innerHTML=p.foods.map((x,i)=>fbHTML(x,i,'food')).join('');E.drinks.innerHTML=p.drinks.map((x,i)=>fbHTML(x,i,'drink')).join('');E.chipEmpty.classList.toggle('hidden',p.chips.length);E.cardEmpty.classList.toggle('hidden',p.cards.length);E.foodEmpty.classList.toggle('hidden',p.foods.length);E.drinkEmpty.classList.toggle('hidden',p.drinks.length);bindOpts()}
function getArr(p,kind){return kind==='chip'?p.chips:kind==='card'?p.cards:kind==='food'?p.foods:p.drinks}
function bindOpts(){document.querySelectorAll('.opt').forEach(el=>{let p=cur(),kind=el.dataset.kind,arr=getArr(p,kind),item=arr.find(x=>x.id===el.dataset.id);el.querySelectorAll('[data-f]').forEach(inp=>inp.oninput=()=>{item[inp.dataset.f]=inp.value;touch()});el.querySelectorAll('[data-check]').forEach(inp=>inp.onchange=()=>{item[inp.dataset.check]=inp.checked;touch()});el.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{let i=arr.findIndex(x=>x.id===item.id),a=b.dataset.act;if(a==='remove')arr.splice(i,1);if(a==='up'&&i>0)[arr[i-1],arr[i]]=[arr[i],arr[i-1]];if(a==='down'&&i<arr.length-1)[arr[i+1],arr[i]]=[arr[i],arr[i+1]];renderOpts();status();touch()})});document.querySelectorAll('[data-img]').forEach(inp=>inp.onchange=async()=>{let f=inp.files&&inp.files[0];if(!f)return;if(f.size>12*1024*1024)return toast('Please use an image under 12 MB');let [kind,id,field]=inp.dataset.img.split(':'),p=cur(),arr=getArr(p,kind),item=arr.find(x=>x.id===id);item[field]=await imageData(f,kind==='chip'?1000:kind==='card'?1200:1100);renderOpts();status();touch();toast('Artwork added')})}
function imageData(file,max){return new Promise((res,rej)=>{let r=new FileReader;r.onerror=rej;r.onload=()=>{let im=new Image;im.onerror=rej;im.onload=()=>{let s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);let x=c.getContext('2d');x.drawImage(im,0,0,c.width,c.height);try{res(c.toDataURL(file.type==='image/png'?'image/png':'image/webp',.88))}catch{res(r.result)}};im.src=r.result};r.readAsDataURL(file)})}
function addChip(){let p=cur();if(!p)return;if(p.chips.length>=10)return toast('Maximum of 10 chip options');p.chips.push({id:uid('chip'),title:'Chip Option '+(p.chips.length+1),denom:'',desc:'',finish:'',ref:'',image:''});renderOpts();status();touch()}
function addCard(){let p=cur();if(!p)return;if(p.cards.length>=10)return toast('Maximum of 10 card options');p.cards.push({id:uid('card'),title:'Card Option '+(p.cards.length+1),stock:'',desc:'',finish:'',ref:'',front:'',back:''});renderOpts();status();touch()}
function addFB(kind){let p=cur();if(!p)return;let arr=kind==='food'?p.foods:p.drinks;arr.push({id:uid(kind),title:'',category:'',desc:'',detail:'',price:'',cost:'',ref:'',image:'',featured:false,priceVisible:false});renderOpts();status();touch()}
const NIUM=[
['Scottish Smoked Salmon','Premium Bites','Potato blinis · dill · molecular caviar'],
['Miniature Beef Cremini Toast','Premium Bites','Brioche · horseradish · pickled mushroom'],
['Smoked Turkey','Premium Bites','Cranberry relish · brioche toast'],
['Petit Choux','Premium Bites','Herb goat cheese · herbs · Parmesan craquelin'],
['Quail Eggs','Premium Bites','Raspberry-shallot confit · brioche toast'],
['Petit Filet Mignon','Premium Bites','Horseradish & French brioche crostini'],
['Modern Tuna Nigiri','Premium Bites','Tuna crudo · ginger cream · gold leaf'],
['Miniature Ahi Poke Wakame Bowl','Premium Bites','Kosho yuzu seasoning · molecular sriracha caviar · micro greens'],
['Curried Chicken Crostini','Premium Bites','Mango chutney · micro greens'],
['Nutmeg Cauliflower Mousseline Éclair','Premium Bites','Parmesan craquelin'],
['Lobster Medallion','High Roller Upgrade','Oscietra caviar · 24K gold'],
['Superfood Quinoa Salad Shaker Jar','Grazing Collection','Quinoa · chickpeas · celery · carrot · baby spinach · white balsamic vinaigrette'],
['Caesar Salad Shaker Jar','Grazing Collection','Traditional organic Caesar salad · creamy dressing · aged Parmesan · housemade croutons'],
['Charcuterie & Cold Cut Display','Grazing Collection','Assorted cured meats served with crostini'],
['Crudité Display','Grazing Collection','Fresh assorted vegetables · ranch dip · hummus'],
['Assorted French Desserts','Sweet Finish','Assortment of miniature tartlets and verrine desserts made in-house from scratch']
];
function loadNium(){let p=cur();if(!p)return;if(p.foods.length&&!confirm('Add the NIUM starter menu to the existing food options?'))return;let existing=new Set(p.foods.map(x=>x.title.toLowerCase()));NIUM.forEach((r,i)=>{if(existing.has(r[0].toLowerCase()))return;p.foods.push({id:uid('food'),title:r[0],category:r[1],desc:r[2],detail:'',price:'',cost:'',ref:'AOC-'+String(i+1).padStart(2,'0'),image:'',featured:['Modern Tuna Nigiri','Miniature Ahi Poke Wakame Bowl','Lobster Medallion','Petit Filet Mignon'].includes(r[0]),priceVisible:false})});renderOpts();status();touch();toast('NIUM culinary starter loaded')}
function buildHTML(mode='interactive'){let p=cur();return p?window.clientHTML(p,esc,fmt,{mode}):''}
function preview(){let html=buildHTML('interactive');if(!html)return;let b=new Blob([html],{type:'text/html'}),u=URL.createObjectURL(b);if(E.frame.dataset.u)URL.revokeObjectURL(E.frame.dataset.u);E.frame.dataset.u=u;E.frame.src=u;E.modal.classList.remove('hidden');document.body.style.overflow='hidden'}
function downloadPortal(){let p=cur();if(!p)return;let html=buildHTML('interactive'),b=new Blob([html],{type:'text/html'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`${safe(p.client||p.event,'client')}-event-experience.html`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200);toast('Client portal HTML created')}
function generate(){let p=cur();if(!p)return;let w=window.open('about:blank','_blank');if(!w){toast('Please allow pop-ups to create the PDF');return}w.document.open();w.document.write(buildHTML('print'));w.document.close();let printed=false,go=()=>{if(printed)return;printed=true;try{w.focus();w.print();toast('Choose Save to PDF in the print dialog')}catch(e){console.error(e);toast('Could not open the PDF dialog')}};let imgs=[...w.document.images];if(!imgs.length||imgs.every(i=>i.complete))setTimeout(go,500);else{let left=imgs.length,done=()=>{left--;if(left<=0)setTimeout(go,300)};imgs.forEach(i=>{if(i.complete)done();else{i.addEventListener('load',done,{once:true});i.addEventListener('error',done,{once:true})}});setTimeout(go,2800)}}
['client','contact','email','phone','event','date','location','label','note'].forEach(k=>E[k].oninput=()=>{let p=cur();if(!p)return;p[k]=E[k].value;if(k==='client'||k==='event')E.title.textContent=p.client||p.event||'Untitled Portal';status();touch()});E.notify.oninput=()=>{let p=cur();if(!p)return;p.notificationEmail=E.notify.value;touch()};
$('newTop').onclick=$('newSide').onclick=$('first').onclick=create;$('addChip').onclick=addChip;$('addCard').onclick=addCard;$('addFood').onclick=()=>addFB('food');$('addDrink').onclick=()=>addFB('drink');$('niumFood').onclick=loadNium;$('preview').onclick=preview;$('downloadPortal').onclick=downloadPortal;$('generate').onclick=generate;$('close').onclick=()=>{E.modal.classList.add('hidden');document.body.style.overflow=''};E.modal.onclick=e=>{if(e.target===E.modal)$('close').click()};
$('dupe').onclick=()=>{let p=cur();if(!p)return;let c=JSON.parse(JSON.stringify(p));c.id=uid('proof');c.label=(c.label||'Round 1')+' Copy';c.created=c.updated=now();S.proofs.unshift(c);S.id=c.id;save();render();toast('Portal duplicated')};
$('del').onclick=()=>{let p=cur();if(!p)return;if(confirm('Delete this client portal?')){S.proofs=S.proofs.filter(x=>x.id!==p.id);S.id=S.proofs[0]?.id||null;save();render();toast('Portal deleted')}};
$('backup').onclick=()=>{let b=new Blob([JSON.stringify({version:3,proofs:S.proofs},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='lvpt-event-experience-studio-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};E.search.oninput=renderList;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!E.modal.classList.contains('hidden'))$('close').click()});
load();S.proofs.sort((a,b)=>new Date(b.updated)-new Date(a.updated));S.id=S.proofs[0]?.id||null;render();
})();
